# Generated by Django 5.1.2 on 2024-10-25 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_alter_healthreport_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthreport',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
