# Generated by Django 5.1.2 on 2024-10-25 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_healthreport_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='healthreport',
            old_name='status',
            new_name='resolved',
        ),
    ]
