# Generated by Django 5.1.2 on 2024-10-31 09:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0005_systemcontact'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemcontact',
            name='health_report',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='reports.healthreport'),
            preserve_default=False,
        ),
    ]
